version: "3.7"
services:
  rabbitMQ:
    image: cyrilix/rabbitmq-mqtt
    ports:
      - "9000:15672"
      - "1883:1883"
      - "5672:5672"
    container_name: rabbitMQ

  nuclio:
    image: nuclio/dashboard:stable-amd64
    ports:
      - "8070:8070"
    container_name: nuclio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  iot-logger:
    ports:
      - "5000:5000"
      - "4444:4444"
    container_name: iot-logger
    volumes:
      - ./iot-logger:/logger
    build:
      context: ./iot-logger
      dockerfile: ./dockerfile
    depends_on:
      - rabbitMQ

  iot-sensors:
    container_name: iot-sensors
    volumes:
      - ./iot-sensors:/sensors
    build:
      context: ./iot-sensors
      dockerfile: ./dockerfile
    depends_on:
      - rabbitMQ
      - iot-logger

  iot-frontend:
    image: httpd:2.4
    ports:
      - "80:80"
    container_name: iot-frontend
    volumes:
      - ./iot-front-end/compiled:/usr/local/apache2/htdocs
    depends_on:
      - iot-logger
