sensors:
  - chat_id: "1"
    name: 'Car'
    sensor_type: "car"
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Circle-icons-car.svg/1200px-Circle-icons-car.svg.png'
    receive_topic_name: 'iot/sensors'
    send_topic_name: 'iot/web/sensors'
    topic_url: 'localhost'
  - chat_id: "2"
    name: 'My house'
    sensor_type: "home"
    image: 'https://www.rawshorts.com/freeicons/wp-content/uploads/2017/01/blue_repicthousebase_1484336386-1.png'
    receive_topic_name: 'iot/sensors'
    send_topic_name: 'iot/web/sensors'
    topic_url: 'localhost'
  - chat_id: "3"
    name: 'Bed room air conditioner'
    sensor_type: "air-conditioner"
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfe3ft1wqiQUu1Kra38EezbmQTljHkFPSPzA&usqp=CAU'
    receive_topic_name: 'iot/sensors'
    send_topic_name: 'iot/web/sensors'
    topic_url: 'localhost'
