id: "1"
name: 'Car'
image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Circle-icons-car.svg/1200px-Circle-icons-car.svg.png'
receive_topic_name: 'iot/sensors'
send_topic_name: 'iot/web/sensors'
topic_url: 'localhost'