chat_id: "2"
name: 'My house'
sensor_type: "home"
image: 'https://www.rawshorts.com/freeicons/wp-content/uploads/2017/01/blue_repicthousebase_1484336386-1.png'
receive_topic_name: 'iot/sensors'
send_topic_name: 'iot/web/sensors'
topic_url: 'localhost'