apiVersion: "nuclio.io/v1"
kind: Function
metadata:
  name: loggerconsumer
  namespace: nuclio
spec:
  handler: "main:handler"
  description: "This function is called when a new message is arrived on the iot/web/sensors queue"
  runtime: "python:3.6"
  image: "nuclio/processor-consumer:latest"
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 75
  triggers:
    MyMqttTrigger:
      kind: rabbit-mq
      url: "amqp://guest:guest@192.168.1.52:5672"
      attributes:
        exchangeName: "\"\""
        queueName: iot/web/sensors
        topics:
          - '""'
  build:
    functionSourceCode: aW1wb3J0IGFzdA0KaW1wb3J0IHJlcXVlc3RzDQoNCg0KZGVmIGhhbmRsZXIoY29udGV4dCwgZXZlbnQpOg0KICAgIGJvZHkgPSBldmVudC5ib2R5LmRlY29kZSgnVVRGLTgnKQ0KICAgIGJvZHkgPSBhc3QubGl0ZXJhbF9ldmFsKGJvZHkuX19zdHJfXygpKQ0KDQogICAgY29udGV4dC5sb2dnZXIuaW5mbyhmJ2JvZHk6IHtib2R5fScpDQoNCiAgICBoZWFkZXJzID0geydDb250ZW50LVR5cGUnOiAiYXBwbGljYXRpb24vanNvbiIsICdBY2NlcHQnOiAiYXBwbGljYXRpb24vanNvbiJ9DQogICAgcGF5bG9hZCA9IHsNCiAgICAgICAgInVzZXJJZCI6IGJvZHlbJ3VzZXJJZCddLA0KICAgICAgICAic2Vuc29yVHlwZSI6IGJvZHlbJ3NlbnNvclR5cGUnXSwNCiAgICAgICAgImNoYXRJZCI6IGJvZHlbJ2NoYXRJZCddLA0KICAgICAgICAibmFtZSI6IGJvZHlbJ25hbWUnXSwNCiAgICAgICAgImltZyI6IGJvZHlbJ2ltZyddLA0KICAgICAgICAicGF5bG9hZCI6IHsNCiAgICAgICAgICAgICJob3VyIjogYm9keVsncGF5bG9hZCddWydob3VyJ10sDQogICAgICAgICAgICAidHlwZSI6IGJvZHlbJ3BheWxvYWQnXVsndHlwZSddLA0KICAgICAgICAgICAgIm1lc3NhZ2UiOiBib2R5WydwYXlsb2FkJ11bJ21lc3NhZ2UnXQ0KICAgICAgICB9DQogICAgfQ0KDQogICAgcmVzcG9uc2UgPSByZXF1ZXN0cy5nZXQoImh0dHA6Ly8xOTIuMTY4LjEuNTk6NDQ0NC9pb3QvbG9nZ2VyL3NlbmRsb2ciLCBoZWFkZXJzPWhlYWRlcnMsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAganNvbj1wYXlsb2FkKQ0KDQogICAgcmV0dXJuIGNvbnRleHQuUmVzcG9uc2UoYm9keT1yZXNwb25zZS5qc29uKCksDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgaGVhZGVycz17fSwNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBjb250ZW50X3R5cGU9J2FwcGxpY2F0aW9uL2pzb24nLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIHN0YXR1c19jb2RlPTIwMCkNCg==
    commands:
      - 'pip install requests==2.25.1'
    codeEntryType: sourceCode
  platform: {}
